trigger: none
pr:
  autoCancel: false

pool:
  vmImage: windows-latest

jobs:
- job: pr_build_test
  steps:
  - task: NuGetCommand@2
    inputs:
      command: restore
      restoreSolution: src/xCache.sln
  - task: VSBuild@1
    inputs:
      solution: src/xCache.sln
  - task: VSTest@2
    inputs:
      testSelector: 'testAssemblies'
      testAssemblyVer2: |
        **\*test*.dll
        !**\*TestAdapter.dll
        !**\obj\**
      searchFolder: '$(System.DefaultWorkingDirectory)'
      runOnlyImpactedTests: false
